import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import * as THREE from 'three';
import {createMachinedGear} from '../src/geometry/gears.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),version=JSON.parse(await readFile(path.join(root,'package.json'),'utf8')).version,output=path.join(root,'output',`scene-product-v${version}`);await mkdir(output,{recursive:true});
const viteEntry=path.join(path.dirname(fileURLToPath(import.meta.resolve('vite/package.json'))),'bin/vite.js');
const server=spawn(process.execPath,[viteEntry,'--host','127.0.0.1','--port','5198','--strictPort'],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});
let browser;const checks=[],records=[],errors=[];
const check=async(name,fn)=>{await fn();checks.push(name);console.log('PASS '+name);};
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Server timeout')),15000);server.stdout.on('data',d=>{if(d.toString().includes('Local:')){clearTimeout(timer);resolve();}});server.on('exit',code=>{clearTimeout(timer);reject(new Error('Server exit '+code));});server.on('error',reject);});
 browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-webgl']});const page=await browser.newPage({viewport:{width:1366,height:768},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5198/src/scene/product-preview.html');await page.waitForFunction(()=>window.qa?.scene);
 await check('Quality levels preserve gear tooth count, radii, bores and helix while reducing sampled surface triangles',()=>{
  const mats=[new THREE.MeshStandardMaterial(),new THREE.MeshStandardMaterial(),new THREE.MeshStandardMaterial()],rows=[];
  for(const detail of ['high','balanced','low']){const gear=createMachinedGear({teeth:62,pitchRadius:1.55,width:.32,boreRadius:.2,steelMaterial:mats[0],faceMaterial:mats[1],darkMaterial:mats[2],detail});let triangles=0;gear.traverse(o=>{if(o.isMesh)triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});const points=gear.children[0].geometry.attributes.position,envelope={minX:Infinity,maxX:-Infinity,minRadius:Infinity,maxRadius:0};for(let i=0;i<points.count;i++){const x=points.getX(i),y=points.getY(i),z=points.getZ(i);assert.ok(Number.isFinite(x)&&Number.isFinite(y)&&Number.isFinite(z));const radius=Math.hypot(y,z);envelope.minX=Math.min(envelope.minX,x);envelope.maxX=Math.max(envelope.maxX,x);envelope.minRadius=Math.min(envelope.minRadius,radius);envelope.maxRadius=Math.max(envelope.maxRadius,radius);}rows.push({detail,triangles,envelope,geometry:gear.userData.gear});gear.traverse(o=>o.geometry?.dispose());}
  for(const r of rows)for(const key of ['teeth','pitchRadius','width','helixDegrees','internal','boreRadius','reliefHoleCount','splinedHub'])assert.deepEqual(r.geometry[key],rows[0].geometry[key],key);
  for(const r of rows)for(const key of ['minX','maxX','minRadius','maxRadius'])assert.ok(Math.abs(r.envelope[key]-rows[0].envelope[key])<1e-6,`physical envelope changes with quality: ${key}`);
  assert.ok(rows[1].triangles<rows[0].triangles*.75);assert.ok(rows[2].triangles<rows[1].triangles*.85);records.push({geometryQuality:rows});mats.forEach(m=>m.dispose());
 });
 await check('All five mechanisms have non-overlapping on-screen labels across narrow, normal and wide views',async()=>{
  for(const type of ['mt','dct','cvt','at','ecvt'])for(const size of [{width:350,height:320},{width:748,height:330},{width:1150,height:480}])for(const camera of ['isometric','front','top']){
   const r=await page.evaluate(async({type,size,camera})=>{const v=document.querySelector('#view');v.style.width=size.width+'px';v.style.height=size.height+'px';await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(qa.sim.settings.type!==type)qa.type(type);qa.scene.setCamera(camera);qa.draw();return new Promise(resolve=>requestAnimationFrame(()=>{qa.draw();const frame=v.getBoundingClientRect(),labels=[...v.querySelectorAll('.scene-part-label')].filter(e=>e.style.display!=='none').map(e=>{const r=e.getBoundingClientRect();return{id:e.dataset.part,left:r.left-frame.left,right:r.right-frame.left,top:r.top-frame.top,bottom:r.bottom-frame.top};});let overlap=0;for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],b=labels[j];if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top)overlap++;}resolve({type,size,camera,labels,overlap,diagnostics:qa.scene.getDiagnostics()});}));},{type,size,camera});
   assert.equal(r.overlap,0,`${type}/${camera}/${size.width}: actual DOM overlap`);assert.ok(r.labels.length>0);for(const l of r.labels)assert.ok(l.left>=-.1&&l.right<=size.width+.1&&l.top>=-.1&&l.bottom<=size.height+.1,`${type}/${camera}: label clipped ${l.id}`);assert.equal(r.diagnostics.performance.labelOverlaps,0);records.push({type,size,camera,labels:r.labels.length,suppressed:r.diagnostics.suppressedLabels});
  }
 });
 await check('Selected components retain visible names and physical-anchor leader lines at dense category settings',async()=>{
  for(const type of ['mt','dct','cvt','at','ecvt']){await page.evaluate(type=>{document.querySelector('#view').style.width='350px';document.querySelector('#view').style.height='320px';qa.type(type);qa.view.focusCategory='clutches';qa.view.selectedPart=type==='cvt'?'secondary':type==='ecvt'?'mg1':type==='at'?'ring':'gear-6';qa.scene.selectPart(qa.view.selectedPart);qa.draw();},type);const r=await page.evaluate(()=>({state:qa.scene.getDiagnostics(),selected:qa.view.selectedPart,label:[...document.querySelectorAll('.scene-part-label')].find(e=>e.dataset.part===qa.view.selectedPart)?.style.display,path:document.querySelector(`[data-leader-part="${qa.view.selectedPart}"]`)?.getAttribute('d')}));assert.equal(r.label,'block');const annotation=r.state.annotations.find(a=>a.id===r.selected);assert.ok(annotation?.selected);assert.ok(r.path?.startsWith(`M ${annotation.anchorX} ${annotation.anchorY} L `));}
  await page.evaluate(()=>{qa.view.focusCategory='all';});
 });
 await check('Names and leader anchors remain fixed while RPM-driven meshes rotate',async()=>{
  await page.evaluate(()=>{qa.type('dct');qa.view.selectedPart='gear-1';qa.draw();});const before=await page.evaluate(()=>qa.scene.getDiagnostics());await page.evaluate(()=>{for(let i=0;i<20;i++)qa.draw(.05);});const after=await page.evaluate(()=>qa.scene.getDiagnostics());
  assert.notEqual(before.rotorAngles[0].angle,after.rotorAngles[0].angle);for(const a of before.annotations){const b=after.annotations.find(b=>b.id===a.id);assert.ok(b);for(const key of ['x','y','anchorX','anchorY'])assert.ok(Math.abs(a[key]-b[key])<.05,`${a.id}:${key} moves with RPM`);}
 });
 await check('One wall-clock second gives the same rotor, belt and oil phase as ten smaller frames',async()=>{
  for(const type of ['mt','dct','cvt','at','ecvt']){const r=await page.evaluate(type=>{qa.view.quality='balanced';qa.type(type);const snapshot=qa.sim.snapshot();qa.scene.update(snapshot,qa.view,1);const single=qa.scene.getDiagnostics();qa.type(type);for(let i=0;i<10;i++)qa.scene.update(snapshot,qa.view,.1);return{type,single,repeated:qa.scene.getDiagnostics()};},type);assert.equal(r.single.rotorAngles.length,r.repeated.rotorAngles.length);for(let i=0;i<r.single.rotorAngles.length;i++){const a=r.single.rotorAngles[i],b=r.repeated.rotorAngles[i];assert.equal(a.key,b.key);assert.ok(Math.abs(Math.atan2(Math.sin(a.angle-b.angle),Math.cos(a.angle-b.angle)))<1e-8,`${type}:${a.key}: speed depends on FPS`);}assert.ok(Math.abs(r.single.beltPhase-r.repeated.beltPhase)<1e-8);for(let i=0;i<r.single.beltSamplePositions.length;i++)for(let j=0;j<3;j++)assert.ok(Math.abs(r.single.beltSamplePositions[i][j]-r.repeated.beltSamplePositions[i][j])<1e-8);for(let i=0;i<r.single.oilPaths.length;i++){assert.ok(Math.abs(r.single.oilPaths[i].phase-r.repeated.oilPaths[i].phase)<1e-8);for(let j=0;j<3;j++)assert.ok(Math.abs(r.single.oilPaths[i].firstDrop[j]-r.repeated.oilPaths[i].firstDrop[j])<1e-8);}records.push({framePhase:type,rotors:r.single.rotorAngles.length,oilRoutes:r.single.oilPaths.length,beltPhase:r.single.beltPhase});}
 });
 await check('Twenty unchanged paused frames skip GPU redraw, while camera, conditions, selection, quality, resize and capture still draw',async()=>{
  const r=await page.evaluate(async()=>{qa.type('dct');qa.view.quality='balanced';qa.view.selectedPart=null;const snapshot=qa.sim.snapshot();for(let i=0;i<6;i++)qa.scene.update(snapshot,qa.view,0);const base=qa.scene.getDiagnostics().performance;for(let i=0;i<20;i++)qa.scene.update(snapshot,qa.view,0);const idle=qa.scene.getDiagnostics().performance;const steps=[];const record=name=>steps.push({name,frames:qa.scene.getDiagnostics().performance.renderFrames});qa.scene.setCamera('front');qa.scene.update(snapshot,qa.view,0);record('camera');qa.sim.setSettings({gear:'3'});const changed=qa.sim.snapshot();qa.scene.update(changed,qa.view,0);record('conditions');qa.view.selectedPart='gear-3';qa.scene.selectPart('gear-3');qa.scene.update(changed,qa.view,0);record('selection');qa.view.quality='low';qa.scene.update(changed,qa.view,0);record('quality');document.querySelector('#view').style.width='732px';await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));qa.scene.update(changed,qa.view,0);record('resize');qa.scene.capture();record('capture');return{base,idle,steps};});assert.equal(r.idle.renderFrames,r.base.renderFrames,'idle pause redraws');assert.equal(r.idle.skippedIdleFrames-r.base.skippedIdleFrames,20);let previous=r.idle.renderFrames;for(const s of r.steps){assert.ok(s.frames>previous,`${s.name} does not redraw`);previous=s.frames;}records.push({pausedRendering:r});
 });
 await check('Quality switching preserves selection, camera, rotor phase and mechanical metadata while reducing actual render load',async()=>{
  const rows=[];await page.evaluate(()=>{document.querySelector('#view').style.width='748px';document.querySelector('#view').style.height='330px';qa.type('dct');qa.view.selectedPart='gear-1';qa.draw(.05);});await page.waitForTimeout(100);
  for(const quality of ['high','balanced','low']){const row=await page.evaluate(quality=>{qa.view.quality=quality;qa.draw();return qa.scene.getDiagnostics();},quality);rows.push(row);assert.equal(row.requestedQuality,quality);assert.equal(row.effectiveQuality,quality);assert.ok(row.annotations.some(a=>a.id==='gear-1'&&a.selected));assert.ok(row.performance.instancedCopies>100);assert.ok(row.meshCount<row.performance.originalMeshes*.8);}
  for(const row of rows.slice(1)){assert.deepEqual(row.partIds,rows[0].partIds);assert.ok(Math.abs(row.cameraDistance-rows[0].cameraDistance)<1e-7);assert.deepEqual(row.rotorAngles,rows[0].rotorAngles);assert.deepEqual(row.gears.map(({detail,...g})=>g),rows[0].gears.map(({detail,...g})=>g));}
  assert.ok(rows[1].triangles<rows[0].triangles*.8);assert.ok(rows[2].triangles<rows[1].triangles*.8);records.push({renderQuality:rows.map(r=>({quality:r.effectiveQuality,meshCount:r.meshCount,...r.performance}))});
 });
 await check('Annotated PNG includes the actual visible names and leader lines and raw PNG remains available',async()=>{
  await page.evaluate(()=>{qa.view.quality='high';qa.view.selectedPart=null;qa.type('dct');});const captures=await page.evaluate(async()=>{const named=qa.scene.capture(),raw=qa.scene.capture({annotations:false});const decode=async url=>{const image=await createImageBitmap(await(await fetch(url)).blob());const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);return ctx.getImageData(0,0,c.width,c.height).data;};const a=await decode(named),b=await decode(raw);let changed=0;for(let i=0;i<a.length;i+=4)if(a[i]!==b[i]||a[i+1]!==b[i+1]||a[i+2]!==b[i+2])changed++;return{named,raw,changed,labels:qa.scene.getDiagnostics().visibleLabels};});assert.ok(captures.changed>1000);assert.ok(captures.labels>0);await writeFile(path.join(output,'dct-annotated.png'),Buffer.from(captures.named.split(',')[1],'base64'));await writeFile(path.join(output,'dct-raw.png'),Buffer.from(captures.raw.split(',')[1],'base64'));
 });
 await check('WebGL interruption shows a recovery action and keeps the same experiment and geometry after restoration',async()=>{
  const before=await page.evaluate(()=>({snapshot:qa.sim.snapshot(),parts:qa.scene.getDiagnostics().partIds}));await page.evaluate(()=>document.querySelector('.transmission-canvas').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await page.waitForFunction(()=>qa.scene.getDiagnostics().contextLost);assert.equal(await page.locator('.scene-graphics-recovery').isVisible(),true);await page.waitForTimeout(250);await page.locator('.scene-graphics-recovery button').click();await page.waitForFunction(()=>!qa.scene.getDiagnostics().contextLost,{timeout:10000});const after=await page.evaluate(()=>{qa.draw();return{snapshot:qa.sim.snapshot(),parts:qa.scene.getDiagnostics().partIds};});assert.deepEqual(after,before);assert.equal(await page.locator('.scene-graphics-recovery').isVisible(),false);
 });
 await page.screenshot({path:path.join(output,'dct-labels.png')});await check('No browser errors',()=>assert.deepEqual(errors,[]));
 const result={checkedAt:new Date().toISOString(),browser:browser.version(),renderEnvironment:'Headless Chromium, ANGLE SwiftShader; these load metrics are not a benchmark of the user GPU.',checks,errors,records};await writeFile(path.join(output,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:checks.length,errors,quality:records.find(r=>r.renderQuality)?.renderQuality},null,2));
}finally{await browser?.close();server.kill();}
